/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Enquiry {
  'id' : bigint,
  'timestampCreated' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
}
export interface Feedback {
  'id' : bigint,
  'suggestions' : string,
  'timestampCreated' : Time,
  'name' : string,
  'email' : string,
  'message' : string,
  'rating' : bigint,
}
export type Time = bigint;
export interface _SERVICE {
  'getAllEnquiries' : ActorMethod<[], Array<Enquiry>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getEnquiry' : ActorMethod<[bigint], Enquiry>,
  'getFeedback' : ActorMethod<[bigint], Feedback>,
  'submitEnquiry' : ActorMethod<[string, string, string], bigint>,
  'submitFeedback' : ActorMethod<
    [string, string, string, bigint, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];